//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sweets.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CustomerOrder
	{
		public virtual int ID
		{
			get;
			set;
		}

		public virtual int Quantity
		{
			get;
			set;
		}

		public virtual DateTime PurchaseDate
		{
			get;
			set;
		}

		public virtual string Email
		{
			get;
			set;
		}

		public virtual string Locality
		{
			get;
			set;
		}

		public virtual string Refinement
		{
			get;
			set;
		}

		public virtual string Wishes
		{
			get;
			set;
		}

		public virtual ICollection<Product> OrderProduts
		{
			get;
			set;
		}

	}
}

