//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sweets.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Product
	{
		public virtual string ProductName
		{
			get;
			set;
		}

		public virtual string Description
		{
			get;
			set;
		}

		public virtual byte[] Photo
		{
			get;
			set;
		}

		public virtual int Quantity
		{
			get;
			set;
		}

		public virtual int ID
		{
			get;
			set;
		}

		public virtual string Weight
		{
			get;
			set;
		}

		public virtual DateTime DateOfChange
		{
			get;
			set;
		}

		public virtual Category Category
		{
			get;
			set;
		}

		public virtual ICollection<CustomerOrder> Orders
		{
			get;
			set;
		}

	}
}

